apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-backend.fullname" . }}
  labels:
    app: django-backend
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: django-backend
