apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-frontend.fullname" . }}
  labels:
    app: react-frontend
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: react-frontend
